<a href="https://colab.research.google.com/github/zainali60/Deep-learning-assignments/blob/main/kears_boston_housing_book_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from keras.datasets import boston_housing
(train_data, train_targets), (test_data, test_targets) = boston_housing.load_data()

In [2]:
train_data.shape

(404, 13)

In [3]:
test_data.shape

(102, 13)

In [4]:
train_targets.shape

(404,)

In [5]:
test_targets.shape

(102,)

In [6]:
train_targets

array([15.2, 42.3, 50. , 21.1, 17.7, 18.5, 11.3, 15.6, 15.6, 14.4, 12.1,
       17.9, 23.1, 19.9, 15.7,  8.8, 50. , 22.5, 24.1, 27.5, 10.9, 30.8,
       32.9, 24. , 18.5, 13.3, 22.9, 34.7, 16.6, 17.5, 22.3, 16.1, 14.9,
       23.1, 34.9, 25. , 13.9, 13.1, 20.4, 20. , 15.2, 24.7, 22.2, 16.7,
       12.7, 15.6, 18.4, 21. , 30.1, 15.1, 18.7,  9.6, 31.5, 24.8, 19.1,
       22. , 14.5, 11. , 32. , 29.4, 20.3, 24.4, 14.6, 19.5, 14.1, 14.3,
       15.6, 10.5,  6.3, 19.3, 19.3, 13.4, 36.4, 17.8, 13.5, 16.5,  8.3,
       14.3, 16. , 13.4, 28.6, 43.5, 20.2, 22. , 23. , 20.7, 12.5, 48.5,
       14.6, 13.4, 23.7, 50. , 21.7, 39.8, 38.7, 22.2, 34.9, 22.5, 31.1,
       28.7, 46. , 41.7, 21. , 26.6, 15. , 24.4, 13.3, 21.2, 11.7, 21.7,
       19.4, 50. , 22.8, 19.7, 24.7, 36.2, 14.2, 18.9, 18.3, 20.6, 24.6,
       18.2,  8.7, 44. , 10.4, 13.2, 21.2, 37. , 30.7, 22.9, 20. , 19.3,
       31.7, 32. , 23.1, 18.8, 10.9, 50. , 19.6,  5. , 14.4, 19.8, 13.8,
       19.6, 23.9, 24.5, 25. , 19.9, 17.2, 24.6, 13

In [7]:
train_data[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [8]:
mean = train_data.mean(axis=0)
train_data -= mean
std = train_data.std(axis=0)
train_data /= std
test_data -= mean
test_data /= std

In [9]:
train_data.shape[1]

13

In [10]:
train_data[0]

array([-0.27224633, -0.48361547, -0.43576161, -0.25683275, -0.1652266 ,
       -0.1764426 ,  0.81306188,  0.1166983 , -0.62624905, -0.59517003,
        1.14850044,  0.44807713,  0.8252202 ])

In [12]:
from keras import models
from keras import layers
def build_model():
  model = models.Sequential()
  model.add(layers.Dense(64, activation='relu',
  input_shape=(train_data.shape[1],)))
  model.add(layers.Dense(64, activation='relu'))
  model.add(layers.Dense(1))
  model.compile(optimizer='rmsprop', loss='mse', metrics=['mae'])
  return model

In [24]:
import numpy as np
k=4
num_val_samples = len(train_data) // k
num_epochs = 100
all_scores = []
for i in range(k):
  print('processing fold #', i)
  val_data = train_data[i * num_val_samples: (i + 1) * num_val_samples]
  val_targets = train_targets[i * num_val_samples: (i + 1) * num_val_samples]
  partial_train_data = np.concatenate([train_data[:i * num_val_samples],train_data[(i + 1) * num_val_samples:]],axis=0)
  partial_train_targets = np.concatenate([train_targets[:i * num_val_samples],train_targets[(i + 1) * num_val_samples:]],axis=0)

  model = build_model()

  model.fit(partial_train_data, partial_train_targets,epochs=num_epochs, batch_size=1, verbose=1)

  val_mse, val_mae = model.evaluate(val_data, val_targets, verbose=0)

  all_scores.append(val_mae)

processing fold # 0
Epoch 1/100
303/303 [==============================] - 14s 1ms/step - loss: 349.3756 - mae: 16.3025
Epoch 2/100
303/303 [==============================] - 0s 1ms/step - loss: 35.4439 - mae: 4.0489
Epoch 3/100
303/303 [==============================] - 0s 1ms/step - loss: 21.6666 - mae: 3.3221
Epoch 4/100
303/303 [==============================] - 0s 1ms/step - loss: 18.4154 - mae: 3.0026
Epoch 5/100
303/303 [==============================] - 0s 1ms/step - loss: 18.6311 - mae: 2.8040
Epoch 6/100
303/303 [==============================] - 0s 1ms/step - loss: 19.9377 - mae: 2.9716
Epoch 7/100
303/303 [==============================] - 0s 1ms/step - loss: 16.7792 - mae: 2.7390
Epoch 8/100
303/303 [==============================] - 0s 1ms/step - loss: 9.6553 - mae: 2.3503
Epoch 9/100
303/303 [==============================] - 0s 1ms/step - loss: 11.2309 - mae: 2.2604
Epoch 10/100
303/303 [==============================] - 0s 1ms/step - loss: 17.1676 - mae: 2.5520
Epoch 1

In [25]:
all_scores

[1.934119701385498, 2.802652597427368, 2.768597364425659, 2.648240804672241]

In [26]:
np.mean(all_scores)

2.5384026169776917

In [13]:
model = build_model()
model.fit(train_data, train_targets,epochs=80, batch_size=16, verbose=0)
test_mse_score, test_mae_score = model.evaluate(test_data, test_targets)

4/4 [==============================] - 1s 4ms/step - loss: 18.3712 - mae: 2.7992


In [14]:
test_mae_score

2.79917049407959